"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# --- dotenv 로드를 위한 import 추가 ---
#from dotenv import load_dotenv 배포때 주석

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- .env 파일 로드 (BASE_DIR 아래 .env 파일) ---
#load_dotenv(os.path.join(BASE_DIR, '.env')) 배포때 주석


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# --- .env 파일에서 SECRET_KEY 가져오기 ---
SECRET_KEY = os.getenv('SECRET_KEY', 'your-default-secret-key-if-not-set') # .env 파일 로드 실패 대비 기본값 추가

# SECURITY WARNING: don't run with debug turned on in production!
# --- 개발 중에는 DEBUG = True 로 설정 ---
DEBUG = True
# 개발중에는 TRUE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# --- ALLOWED_HOSTS 설정 (DEBUG=True 일 때는 '*' 와 동일하게 동작) ---
# 실제 배포 시에는 DEBUG=False 로 바꾸고, 필요한 도메인/IP만 정확히 적어야 합니다.
ALLOWED_HOSTS = ['kill.ploti.kr', '222.239.218.185', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'generator', # 생성한 앱 추가
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # @csrf_exempt 를 사용하므로 필요 없을 수 있으나 유지
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # --- templates 폴더 경로 설정 ---
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
# --- 실제 배포 환경에서 정적 파일을 모으는 경로 ---
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# 개발 중에 사용할 정적 파일 폴더 (필요시 주석 해제하여 사용)
# STATICFILES_DIRS = [ BASE_DIR / "static", ]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 미디어 파일 설정 (사용자가 업로드한 파일)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # BASE_DIR / 'media' 와 동일